/** Países con proxy automático disponible en Unipile (ISO 3166-1 alpha-2). */
export const UNIPILE_PROXY_COUNTRY_CODES = [
  "ar",
  "at",
  "au",
  "be",
  "br",
  "ca",
  "ch",
  "cl",
  "cn",
  "co",
  "cy",
  "cz",
  "de",
  "dk",
  "ee",
  "eg",
  "es",
  "fi",
  "fr",
  "gb",
  "gt",
  "hk",
  "id",
  "ie",
  "il",
  "in",
  "it",
  "jp",
  "kr",
  "kz",
  "ma",
  "mx",
  "my",
  "nl",
  "no",
  "pa",
  "pk",
  "pl",
  "pr",
  "pt",
  "ro",
  "sa",
  "se",
  "sg",
  "th",
  "tn",
  "tr",
  "ua",
  "us",
  "vn",
  "za",
  "ae",
  "ao",
  "bd",
  "bg",
] as const;

export type UnipileProxyCountryCode = (typeof UNIPILE_PROXY_COUNTRY_CODES)[number];

const COUNTRY_LABELS_ES: Record<UnipileProxyCountryCode, string> = {
  ar: "Argentina",
  at: "Austria",
  au: "Australia",
  be: "Bélgica",
  br: "Brasil",
  ca: "Canadá",
  ch: "Suiza",
  cl: "Chile",
  cn: "China",
  co: "Colombia",
  cy: "Chipre",
  cz: "Chequia",
  de: "Alemania",
  dk: "Dinamarca",
  ee: "Estonia",
  eg: "Egipto",
  es: "España",
  fi: "Finlandia",
  fr: "Francia",
  gb: "Reino Unido",
  gt: "Guatemala",
  hk: "Hong Kong",
  id: "Indonesia",
  ie: "Irlanda",
  il: "Israel",
  in: "India",
  it: "Italia",
  jp: "Japón",
  kr: "Corea del Sur",
  kz: "Kazajistán",
  ma: "Marruecos",
  mx: "México",
  my: "Malasia",
  nl: "Países Bajos",
  no: "Noruega",
  pa: "Panamá",
  pk: "Pakistán",
  pl: "Polonia",
  pr: "Puerto Rico",
  pt: "Portugal",
  ro: "Rumanía",
  sa: "Arabia Saudita",
  se: "Suecia",
  sg: "Singapur",
  th: "Tailandia",
  tn: "Túnez",
  tr: "Turquía",
  ua: "Ucrania",
  us: "Estados Unidos",
  vn: "Vietnam",
  za: "Sudáfrica",
  ae: "Emiratos Árabes Unidos",
  ao: "Angola",
  bd: "Bangladesh",
  bg: "Bulgaria",
};

export const UNIPILE_PROXY_COUNTRY_OPTIONS = UNIPILE_PROXY_COUNTRY_CODES.map(
  (code) => ({
    value: code,
    label: COUNTRY_LABELS_ES[code],
  })
);

export function isUnipileProxyCountryCode(
  value: string
): value is UnipileProxyCountryCode {
  return (UNIPILE_PROXY_COUNTRY_CODES as readonly string[]).includes(value);
}
